name: test markdown


on:
  push:
    branches: [ "main" ]
    tags:  v1.*


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 


      - name: Markdown link extract to json
        uses: mipmip/github-action-markdown-link-extract-to-json@v1.5
        with:
          in-file: releasenotes.md
          out-file: releasenotes.json
          section: 'main'

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: releasenotes
          path: releasenotes.json


