name: test markdown


on:
  push:
    branches: [ "main" ]
    tags:  v1.*


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 

      - uses: markpatterson27/markdown-to-output@v1
        id: md
        with:
          filepath: releasenotes.md

      - run: |
          echo ${{ steps.md.outputs.attributes }}
          echo ${{ steps.md.outputs.body }}


      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{github.ref_name}}
          name: ${{github.ref_name}}
          prerelease: false
          draft: false
