name: test markdown


on:
  push:
    branches: [ "main" ]
    tags:  v1.*


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 

      - uses: kkurno/action-markdown-reader@v0.1.0
        id: markdown
        with:
          markdown: releasenotes.md

      - run: |
          echo  ${{ toJSON(steps.markdown.outputs.data) }}



