name: test markdown


on:
  push:
    branches: [ "main" ]
    tags:  v1.*


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
     
      - uses: actions/setup-go@v3
        with:
          go-version: '1.17'

      - name: Install depandency
        run: |
          go install github.com/eclipse/paho.mqtt.golang@v1.4.2
          go install github.com/sirupsen/logrus@v1.9.0
          go install gonum.org/v1/gonum@v0.12.0
          go install google.golang.org/protobuf@v1.28.1
          
      - name: note
        shell: python 
        run: |
          import os;f=open('releasenotes.md',"r");obj={i[0].strip():i[1:] for i in [i.split('-') for i in f.read().split('##')[1:]]};f.close()
          note=[obj[i] for i in obj if i=='${{github.ref_name}}'];note=[note[0] if note else ''][0]
          os.system("echo 'NOTE<<EOF' >> $GITHUB_ENV")
          tmp=[os.system("echo '{}' >> $GITHUB_ENV".format(n.strip())) for n in note ]
          os.system("echo 'EOF' >> $GITHUB_ENV")
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{github.ref_name}}
          name: ${{github.ref_name}}
          body: ${{env.NOTE}}


