name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]
      
    runs-on: ${{ matrix.os }}
    steps:
      - uses: PxyUp/protoc-actions@v3.0.0
      - name: Install Protoc
        with:
          path: -I./ --go_opt=paths=source_relative --go_out=./generated cmakepresets/test.proto
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-${{ matrix.os }}
          path: .
