name: hosted-ninja-vcpkg_submod-autocache


on:
  push:
    branches: [ "main" ]
    tags:  v1.*


jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]


    steps:
      - uses: actions/checkout@v3
      - name: Get Branch
        run: echo -e "${github.event.ref}"

          
