name: hosted-ninja-vcpkg_submod-autocache


on:
  push:
    branches: [ "main" ]
    tags:  v1.*


jobs:
  job:
    name: ${{github.ref#refs/heads/}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]


    steps:
      - uses: actions/checkout@v3


          
