name: hosted-ninja-vcpkg_submod-autocache


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  job:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest]
        include:
          - os: "windows-latest"
            vcpkgCommitId: '253704407ae68efa37bf8f5b59b3e06dd40d3d3f'
            triplet: x64-windows-static
    env:
      VCPKG_DEFAULT_TRIPLET: ${{ matrix.triplet }}

    steps:
      - uses: actions/checkout@v3

       
      - name: add vcdll 
        run : |
          ls C:/Windows/system32/msvcp140*
        
