name: hosted-ninja-vcpkg_submod-autocache


on:
  push:
    branches: [ "main" ]
    tags:  v1.*


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ${{github.ref_name}}
        uses: actions/checkout@v2

      - name: Release
        with:
          tag_name: ${{ github.ref }}
          name:  ${{ github.ref }}
          body: TODO New Release.
          draft: false
          prerelease: false
